import { useEffect, useRef, useState } from 'react';
import { X, Wand2 } from 'lucide-react';
import { useTripContext } from '../context/TripContext';
import { autoGenerateDrivingRoutes } from '../firebase/tripService';

interface Toast {
  id: string;
  message: string;
  type: 'info' | 'hotel';
}

export default function ToastNotifications() {
  const {
    restaurants,
    highlights,
    photos,
    packingItems,
    travelLog,
    currentMember,
    hotelChangeBanner,
    dismissHotelBanner,
    tripCode,
    hotels,
    flights,
    driving,
    isAdmin,
  } = useTripContext();

  const [toasts, setToasts] = useState<Toast[]>([]);

  const prevRestaurantsLen = useRef<number | null>(null);
  const prevHighlightsLen = useRef<number | null>(null);
  const prevPhotosLen = useRef<number | null>(null);
  const prevPackingLen = useRef<number | null>(null);
  const prevTravelLogLen = useRef<number | null>(null);
  const initialized = useRef(false);

  const addToast = (message: string, type: Toast['type'] = 'info') => {
    const id = `toast-${Date.now()}-${Math.random()}`;
    setToasts((prev) => [...prev.slice(-2), { id, message, type }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 4000);
  };

  const removeToast = (id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  };

  // Initialize refs on first render (skip "new" detection for initial load)
  useEffect(() => {
    if (!initialized.current) {
      prevRestaurantsLen.current = restaurants.length;
      prevHighlightsLen.current = highlights.length;
      prevPhotosLen.current = photos.length;
      prevPackingLen.current = packingItems.length;
      prevTravelLogLen.current = travelLog.length;
      initialized.current = true;
    }
  }, []);

  // Watch restaurants
  useEffect(() => {
    if (!initialized.current) return;
    const prev = prevRestaurantsLen.current;
    if (prev !== null && restaurants.length > prev) {
      const newest = [...restaurants].sort((a, b) =>
        (b as any).createdAt > (a as any).createdAt ? 1 : -1
      )[0];
      const name = newest?.name || '';
      // Skip if current member added it (best-effort check)
      addToast(`📍 New restaurant added${name ? ': ' + name : ''}`);
    }
    prevRestaurantsLen.current = restaurants.length;
  }, [restaurants.length]);

  // Watch highlights
  useEffect(() => {
    if (!initialized.current) return;
    const prev = prevHighlightsLen.current;
    if (prev !== null && highlights.length > prev) {
      const newest = highlights[highlights.length - 1];
      addToast(`⭐ New highlight added${newest?.name ? ': ' + newest.name : ''}`);
    }
    prevHighlightsLen.current = highlights.length;
  }, [highlights.length]);

  // Watch photos
  useEffect(() => {
    if (!initialized.current) return;
    const prev = prevPhotosLen.current;
    if (prev !== null && photos.length > prev) {
      const newest = [...photos].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())[0];
      const isOwn = newest?.memberId === currentMember?.id;
      if (!isOwn) addToast('📷 New photo added');
    }
    prevPhotosLen.current = photos.length;
  }, [photos.length]);

  // Watch packing items
  useEffect(() => {
    if (!initialized.current) return;
    const prev = prevPackingLen.current;
    if (prev !== null && packingItems.length > prev) {
      const newest = packingItems[packingItems.length - 1];
      addToast(`🧳 New packing item${newest?.text ? ': ' + newest.text : ''}`);
    }
    prevPackingLen.current = packingItems.length;
  }, [packingItems.length]);

  // Watch travel log
  useEffect(() => {
    if (!initialized.current) return;
    const prev = prevTravelLogLen.current;
    if (prev !== null && travelLog.length > prev) {
      addToast('📖 New travel log entry');
    }
    prevTravelLogLen.current = travelLog.length;
  }, [travelLog.length]);

  async function handleGenerateRoutes() {
    if (!tripCode) return;
    dismissHotelBanner();
    try {
      await autoGenerateDrivingRoutes(tripCode, hotels, flights, driving);
      addToast('🗺️ Driving routes updated!');
    } catch {
      addToast('⚠️ Failed to generate routes');
    }
  }

  return (
    <>
      {/* Hotel change banner */}
      {isAdmin && hotelChangeBanner && (
        <div className="hotel-banner">
          <span>🏨 Hotels updated — regenerate driving routes?</span>
          <div className="hotel-banner-actions">
            <button className="hotel-banner-btn primary" onClick={handleGenerateRoutes}>
              <Wand2 size={14} />
              Generate Now
            </button>
            <button className="hotel-banner-btn" onClick={dismissHotelBanner}>
              Dismiss
            </button>
          </div>
        </div>
      )}

      {/* Toast stack */}
      <div className="toast-container">
        {toasts.map((toast) => (
          <div key={toast.id} className="toast toast-enter">
            <span>{toast.message}</span>
            <button className="toast-close" onClick={() => removeToast(toast.id)}>
              <X size={14} />
            </button>
          </div>
        ))}
      </div>
    </>
  );
}
